# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    admin.activity:
        class: AppBundle\Admin\ActivityAdmin
        arguments: [~, AppBundle\Entity\Activity, ~]
        tags:
            - {name: sonata.admin, manager_type: orm, label: Activités }
    #sonata.user.admin.user:
     #   class: Application\Sonata\UserBundle\Admin\UserAdmin
      #  arguments: [~, Application\Sonata\UserBundle\Entity\User, ~]
       # tags:
        #    - {name: sonata.admin, manager_type: orm, label: Users }
